spring.application.name=exMVC

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/hrd
spring.datasource.username=postgres
spring.datasource.password=1234

mybatis.mapper-locations=classpath:mapper/*.xml
